### ISSUE TITLE
Manjaro Linux: Libsecret not recognized

### ISSUE THREAD

**Issue by technodrome** [notpushkin/Mailspring-Libre#43]
**Describe the bug**
Fresh install from AUR. Upon first launch, an error message appears. User can only quit the app. See error in screenshot.

**To Reproduce**
1. Install AUR package
2. Run
3. See error

**Expected behavior**
Working state.

**Screenshots**
![image](https://user-images.githubusercontent.com/3662386/103034799-05219600-4566-11eb-96ba-1f7200e25b45.png)

**Setup: (please complete the following information):**
 - OS: Manjaro Linux
 - OS Version 5.4.80-2-MANJARO #1 SMP PREEMPT Sat Nov 28 09:58:18 UTC 2020 x86_64 GNU/Linux
 - Mailspring Version: ex: 1.7.8_libre1
 - libsecret installed: 0.20.4-1

**Comment by exprez135** [comment]
Hmm, thanks for the report! I'll see if I can boot up my Manjaro computer later today, but I don't think I've run into this issue. Do you have gnome-keyring installed? It is marked as an optional dependency, but it's possible that it's currently required by the Linux package.

**Comment by technodrome** [comment]
Thanks for your reply. My Manjaro uses kdewallet (as I have KDE installed) to manage keys AFAIK. Installing yet another key manager just to have one app working isn't very user friendly in my book. Shouldn't this be abstracted so that it doesn't require any specific key manager?

**Comment by exprez135** [comment]
I agree completely! Just wanted to be sure that was the issue.
There's at least one issue upstream about this as well (https://github.com/Foundry376/Mailspring/issues/713). I will try to look into this soon.

**Comment by technodrome** [comment]
Thank you. It is indeed a sloppy implementation on their side. I'll give this gladly a go as soon as this is fixed.

**Comment by exprez135** [comment]
Okay I've done a lot more reading on this. I'm not sure where to go from here. I have every desire to get this working without requiring gnome-keyring, but I don't know if this project would have the bandwidth to do so.

KDE never finished replacing KWallet with a Secret Service API-compatible solution, which leaves us without any secure options. As far as I can see, node-keytar --> libsecret --> a keyring is the standard for secrets management in node now. If KDE ever finishes KSecretService, then everything will work properly.

I personally don't have the expertise to write something which will interact with the KWallet dbus as a fallback. If anyone knows of a library like Python's keyring which supports macOS Keychain, the Secret Service API, Windows Credential Locker, **and** KWallet, let me know!

**Comment by lannet2000** [comment]
On  Manjaro KDE I fixed it installing gnome-keyring and it work good :)

**Comment by wcasanova** [comment]
> Thanks for your reply. My Manjaro uses kdewallet (as I have KDE installed) to manage keys AFAIK. Installing yet another key manager just to have one app working isn't very user friendly in my book. Shouldn't this be abstracted so that it doesn't require any specific key manager?

You should not force to use gnome-keyring, it is better to use org.freedesktop.secrets (secret storage backend) in my case I use KeePassXC in kde and for some reason it does not work with Mailspring

**Comment by JoshuaCrewe** [comment]
I have gnome-keyring installed and I still get this error. It was working previously on this system but I needed to reinstall the app. Also on Arch linux and installed via the AUR.

**Comment by wcasanova** [comment]
> On Manjaro KDE I fixed it installing gnome-keyring and it work good :)

you can also use KeePassXC
https://www.cogitri.dev/posts/03-keepassxc-freedesktop-secret/#setting-up-within-keepassxc
https://rtfm.co.ua/en/what-is-linux-keyring-gnome-keyring-secret-service-and-d-bus/

**Comment by JoshuaCrewe** [comment]
I tried installing KeePassXC but that didn't solve the problem either.

I am happy to install gnome-keyring if that is what is required but at the moment I have that installed along with libsecret and I still get an error saying they need to be installed.

Any ideas what is going on?

**Comment by sandboiii** [comment]
I also had problem with libsecret. Installing gnome-keyring is not enough. You need to make sure that keyring-daemon is running. Please read the [wiki for this matter](https://wiki.archlinux.org/index.php/GNOME/Keyring#Using_the_keyring_outside_GNOME). I used the PAM method and Mailspring is now working good for me.

**Comment by JoshuaCrewe** [comment]
I found in the end doing what is found https://github.com/Foundry376/Mailspring/issues/511#issuecomment-363842150 was enough to get it working for me. I was going down the `.xinitrc` route. The additional `dbus-update-activation-environment --systemd DISPLAY` appeared to be required for me.

**Comment by flazz01** [comment]
Im facing the same issue. And still cant find a fix.

**Comment by JoshuaCrewe** [comment]
@flazz01 are you aware that the original project which this is forked from is now fully open source and doesn't require an ID to use? It might be worth trying that one out to see if you still have the same issue or not.

**Comment by ashooner** [comment]
@JoshuaCrewe This issue also occurs when using Mailspring 1.9.2-1 (not Libre) on Manjaro.

**Comment by TristanK27** [comment]
Just tested with flatpak as well as the AUR package and both still give this error.
